version: '3'
services:
  backend:
    build: ./src  # Asegúrate de que este path sea correcto
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
